clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  eslint:
    group: install
    image: marcbachmann/eslint:5.10.0
    secrets: [gh_token]

  install:
    group: install
    image: node:8-alpine
    commands: ["npm install"]

  test-node-8:
    group: test
    image: node:8-alpine
    commands: ["npm run test:ci -s"]

  test-node-10:
    group: test
    image: node:10-alpine
    commands: ["npm run test:ci -s"]

  test-node-11:
    group: test
    image: node:11-alpine
    commands: ["npm run test:ci -s"]

  publish:
    group: build
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token, npm_token]
