---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:7.14.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: node:14-alpine
  commands: ["npm install"]

- name: test-node-14
  image: node:14-alpine
  commands: ["npm run test:ci -s"]

- name: test-node-16
  image: node:16-alpine
  commands: ["npm run test:ci -s"]

- name: test-node-17
  image: node:17-alpine
  commands: ["npm run test:ci -s"]

- name: publish
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

---
kind: signature
hmac: 51b7b6c58ea6ba047c20b42ea0d012b4431207211470076c285ab5ad085d45f1

...
